# Configuration for the main render pipeline of the application.

# ----- 
# Pattern layers.
#

# Very basic pattern to play with. See file /shader/simple.frag
render/simple:
  shader: simple

# Flexible perlin noise.
render/perlin:
  shader: perlin

# Audio pattern layer
render/audio:
  shader: audio
  texture/src:
    buffer: audio_input

# TODO: Add video & image layers.

# 
# Linear Render pipeline
#
render/mixer:
  shader: mixer
  texture/src: simple
  texture/src1: perlin

render/colourize:
  shader: colourize
  texture/src: mixer
  texture/palette:
    buffer: palette 

render/correct:
  shader: correct
  texture/src:
    buffer: colourize

render/lamps:
  shader: none
  texture/src: correct

